/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppResourcesIndexRouteImport } from './routes/_app/resources/index'
import { Route as AppResourcesResourceIdRouteImport } from './routes/_app/resources/$resourceId'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIndexRoute = AppResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesResourceIdRoute = AppResourcesResourceIdRouteImport.update({
  id: '/resources/$resourceId',
  path: '/resources/$resourceId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/resources/$resourceId': typeof AppResourcesResourceIdRoute
  '/resources/': typeof AppResourcesIndexRoute
  '/signin': typeof AuthSigninRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/resources/$resourceId': typeof AppResourcesResourceIdRoute
  '/resources': typeof AppResourcesIndexRoute
  '/signin': typeof AuthSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/resources/$resourceId': typeof AppResourcesResourceIdRoute
  '/_app/resources/': typeof AppResourcesIndexRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_base/': typeof BaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/resources/$resourceId'
    | '/resources/'
    | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/resources/$resourceId'
    | '/resources'
    | '/signin'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_base'
    | '/_app/dashboard'
    | '/_app/resources/$resourceId'
    | '/_app/resources/'
    | '/_auth/signin'
    | '/_base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/': {
      id: '/_app/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AppResourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/$resourceId': {
      id: '/_app/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof AppResourcesResourceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppResourcesResourceIdRoute: typeof AppResourcesResourceIdRoute
  AppResourcesIndexRoute: typeof AppResourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppResourcesResourceIdRoute: AppResourcesResourceIdRoute,
  AppResourcesIndexRoute: AppResourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BaseRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
