/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppWorkshopsIndexRouteImport } from './routes/_app/workshops/index'
import { Route as AppParticipantsIndexRouteImport } from './routes/_app/participants/index'
import { Route as AppWorkshopsWorkshopIdRouteImport } from './routes/_app/workshops/$workshopId'
import { Route as AppParticipantsParticipantIdRouteImport } from './routes/_app/participants/$participantId'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsIndexRoute = AppWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsIndexRoute = AppParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkshopsWorkshopIdRoute = AppWorkshopsWorkshopIdRouteImport.update({
  id: '/workshops/$workshopId',
  path: '/workshops/$workshopId',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsParticipantIdRoute =
  AppParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/signin': typeof AuthSigninRoute
  '/participants/$participantId': typeof AppParticipantsParticipantIdRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/participants/': typeof AppParticipantsIndexRoute
  '/workshops/': typeof AppWorkshopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/feedback': typeof AppFeedbackRoute
  '/signin': typeof AuthSigninRoute
  '/participants/$participantId': typeof AppParticipantsParticipantIdRoute
  '/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/participants': typeof AppParticipantsIndexRoute
  '/workshops': typeof AppWorkshopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_base/': typeof BaseIndexRoute
  '/_app/participants/$participantId': typeof AppParticipantsParticipantIdRoute
  '/_app/workshops/$workshopId': typeof AppWorkshopsWorkshopIdRoute
  '/_app/participants/': typeof AppParticipantsIndexRoute
  '/_app/workshops/': typeof AppWorkshopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/feedback'
    | '/signin'
    | '/participants/$participantId'
    | '/workshops/$workshopId'
    | '/participants/'
    | '/workshops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/feedback'
    | '/signin'
    | '/participants/$participantId'
    | '/workshops/$workshopId'
    | '/participants'
    | '/workshops'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_base'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/feedback'
    | '/_auth/signin'
    | '/_base/'
    | '/_app/participants/$participantId'
    | '/_app/workshops/$workshopId'
    | '/_app/participants/'
    | '/_app/workshops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/': {
      id: '/_app/workshops/'
      path: '/workshops'
      fullPath: '/workshops/'
      preLoaderRoute: typeof AppWorkshopsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/participants/': {
      id: '/_app/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof AppParticipantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workshops/$workshopId': {
      id: '/_app/workshops/$workshopId'
      path: '/workshops/$workshopId'
      fullPath: '/workshops/$workshopId'
      preLoaderRoute: typeof AppWorkshopsWorkshopIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/participants/$participantId': {
      id: '/_app/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof AppParticipantsParticipantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppParticipantsParticipantIdRoute: typeof AppParticipantsParticipantIdRoute
  AppWorkshopsWorkshopIdRoute: typeof AppWorkshopsWorkshopIdRoute
  AppParticipantsIndexRoute: typeof AppParticipantsIndexRoute
  AppWorkshopsIndexRoute: typeof AppWorkshopsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppParticipantsParticipantIdRoute: AppParticipantsParticipantIdRoute,
  AppWorkshopsWorkshopIdRoute: AppWorkshopsWorkshopIdRoute,
  AppParticipantsIndexRoute: AppParticipantsIndexRoute,
  AppWorkshopsIndexRoute: AppWorkshopsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BaseRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
